/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MVC_JugarTurno;

import dtos.CartaDTO;

/**
 *
 * @author saula
 */
public class PanelCarta extends javax.swing.JPanel {

    private CartaDTO carta;

    public PanelCarta() {
        initComponents();
    }
    
    /**
     * Creates new form PanelCarta
     */
    public PanelCarta(CartaDTO cartaDTO) {
        initComponents();
        this.carta= cartaDTO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImgCarta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 84, 182));
        setLayout(new java.awt.BorderLayout());

        lblImgCarta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unoCard.png"))); // NOI18N
        lblImgCarta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImgCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgCartaMouseClicked(evt);
            }
        });
        add(lblImgCarta, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("panelCarta");
    }// </editor-fold>//GEN-END:initComponents

    private void lblImgCartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgCartaMouseClicked
        System.out.println(carta.toString());
    }//GEN-LAST:event_lblImgCartaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImgCarta;
    // End of variables declaration//GEN-END:variables
}
