package MVC_JugarTurno;

import DTOs.CartaDTO;
import DTOs.EstadoPartidaDTO;
import Enums.TipoColor;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Abraham Coronel
 */
public class PantallaTurno extends javax.swing.JFrame implements ISuscriptor {

    private static final int CARD_W = 95;
    private static final int CARD_H = 130;
    private static final int OVERLAP = 20;   // es lo que se desplaza la carta para empalmarse
    private static final int PAD_L = OVERLAP; // para que la primera se vea completa
    private static final int PAD_R = 10;
    private final UnoSpinControlador control;
    private final IModeloVista modelo;
    private boolean pidiendoColor = false;

    public PantallaTurno(IModeloVista modelo, UnoSpinControlador control) {
        this.control = control;
        this.modelo = modelo;
        initComponents();
        configurarScroll();
        configurarPanelMano();
        configurarEventosScroll();

        configurarCarruselMano(7);
        ajustarAnchoMano();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        panelSur = new javax.swing.JPanel();
        panelInfoJugadorPrincipal = new MVC_JugarTurno.PanelInformacionJugador();
        scrollMano = new javax.swing.JScrollPane();
        panelMano = new javax.swing.JPanel();
        panelOeste = new javax.swing.JPanel();
        panelInfoJugador3 = new MVC_JugarTurno.PanelInformacionJugador();
        panelNorte = new javax.swing.JPanel();
        panelInfoJugador2 = new MVC_JugarTurno.PanelInformacionJugador();
        panelEste = new javax.swing.JPanel();
        panelInfoJugador1 = new MVC_JugarTurno.PanelInformacionJugador();
        panelCentral = new javax.swing.JPanel();
        tablero = new javax.swing.JLayeredPane();
        lblRuleta = new javax.swing.JLabel();
        panelPosaCartas = new javax.swing.JPanel();
        panelDescarte = new MVC_JugarTurno.PanelCarta();
        panelMazo = new MVC_JugarTurno.PanelCarta();

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 84, 182));

        panelFondo.setLayout(new java.awt.BorderLayout());

        panelSur.setBackground(new java.awt.Color(31, 84, 182));
        panelSur.add(panelInfoJugadorPrincipal);

        scrollMano.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollMano.setMaximumSize(new java.awt.Dimension(100, 100));
        scrollMano.setViewportView(panelMano);

        panelSur.add(scrollMano);

        panelFondo.add(panelSur, java.awt.BorderLayout.PAGE_END);

        panelOeste.setBackground(new java.awt.Color(31, 84, 182));
        panelOeste.add(panelInfoJugador3);

        panelFondo.add(panelOeste, java.awt.BorderLayout.LINE_START);

        panelNorte.setBackground(new java.awt.Color(31, 84, 182));
        panelNorte.add(panelInfoJugador2);

        panelFondo.add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelEste.setBackground(new java.awt.Color(31, 84, 182));
        panelEste.add(panelInfoJugador1);

        panelFondo.add(panelEste, java.awt.BorderLayout.LINE_END);

        panelCentral.setBackground(new java.awt.Color(31, 84, 182));

        tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRuleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta.png"))); // NOI18N
        lblRuleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tablero.add(lblRuleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 425));

        panelMazo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMazoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPosaCartasLayout = new javax.swing.GroupLayout(panelPosaCartas);
        panelPosaCartas.setLayout(panelPosaCartasLayout);
        panelPosaCartasLayout.setHorizontalGroup(
            panelPosaCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPosaCartasLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelDescarte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPosaCartasLayout.setVerticalGroup(
            panelPosaCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPosaCartasLayout.createSequentialGroup()
                .addGroup(panelPosaCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDescarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tablero.setLayer(panelPosaCartas, javax.swing.JLayeredPane.PALETTE_LAYER);
        tablero.add(panelPosaCartas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, 130));

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablero)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablero)
        );

        panelFondo.add(panelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMazoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMazoMouseClicked
        control.robarCarta();
    }//GEN-LAST:event_panelMazoMouseClicked

    private void configurarCarruselMano(int cartasVisibles) {
        int step = CARD_W - OVERLAP; // cuánto “avanza” cada carta
        int visibleW = PAD_L + CARD_W + (cartasVisibles - 1) * step + PAD_R;
        int visibleH = CARD_H + 20; // un poquito extra por margen

        scrollMano.setPreferredSize(new java.awt.Dimension(visibleW, visibleH));
        scrollMano.setMinimumSize(new java.awt.Dimension(visibleW, visibleH));

        // para que se aplique
        scrollMano.revalidate();
    }

    private void configurarScroll() {
        scrollMano.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollMano.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        // ocultar visualmente la barra
        scrollMano.getHorizontalScrollBar().setPreferredSize(new java.awt.Dimension(0, 0));

        scrollMano.setOpaque(false);
        scrollMano.getViewport().setOpaque(false);
        scrollMano.setBorder(null);
    }

    private void configurarPanelMano() {
        // Solapado real (gap negativo)
        panelMano.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, -OVERLAP, 0));

        // margen para que la primera carta se vea completa
        panelMano.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, PAD_L, 0, PAD_R));
        panelMano.setOpaque(false);
    }

    private void configurarEventosScroll() {
        scrollMano.addMouseWheelListener(e -> {
            javax.swing.JScrollBar bar = scrollMano.getHorizontalScrollBar();
            bar.setValue(bar.getValue() + e.getWheelRotation() * 45);
            e.consume();
        });
    }

    private void mostrarMano(java.util.List<PanelCartaMano> cartas) {
//        panelMano.removeAll();
//
//        for (PanelCarta c : cartas) {
//            panelMano.add(c);
//        }
//
//        ajustarAnchoMano();
        panelMano.removeAll();
        for (PanelCartaMano c : cartas) {
            panelMano.add(c);
        }
        ajustarAnchoMano();
    }

    private void ajustarAnchoMano() {
        int n = panelMano.getComponentCount();

        int step = CARD_W - OVERLAP; // avance real por carta
        int width = PAD_L + (n == 0 ? 0 : (CARD_W + (n - 1) * step)) + PAD_R;
        int height = CARD_H + 10;

        panelMano.setPreferredSize(new java.awt.Dimension(width, height));
        panelMano.revalidate();
        panelMano.repaint();
    }

    public void mostrarMensaje(String mensaje, String titulo, int tipoMensaje) {
        JOptionPane.showMessageDialog(
                this,
                mensaje,
                titulo,
                tipoMensaje
        );
    }

    public void mostrarError(String mensaje) {
        mostrarMensaje(mensaje, "Movimiento no permitido", javax.swing.JOptionPane.WARNING_MESSAGE);
    }

    public int mostrarOpciones(String mensaje, String titulo, Object[] opciones) {
        return JOptionPane.showOptionDialog(this, mensaje, titulo,
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, opciones, opciones[0]);
    }

    private void pedirColorUsuario() {
        TipoColor[] colores = {
            TipoColor.ROJO, TipoColor.AZUL,
            TipoColor.VERDE, TipoColor.AMARILLO
        };
        int seleccion = mostrarOpciones("Has jugado un comodin. Selecciona el nuevo color:", "Cambio de Color", colores);
        if (seleccion >= 0) {
            control.seleccionarColor(colores[seleccion]);
        }
        pidiendoColor = false;
    }

    private List<PanelCartaMano> generarPanelesDeMano(List<CartaDTO> cartasDTO) {
//        List<PanelCarta> paneles = new java.util.ArrayList<>();
//
//        for (CartaDTO cartaDTO : cartasDTO) {
//            PanelCarta panel = new PanelCarta();
//
//            panel.addMouseListener(new java.awt.event.MouseAdapter() {
//                @Override
//                public void mouseClicked(java.awt.event.MouseEvent evt) {
//                    intentarJugarCarta(cartaDTO);
//                }
//            });
//
//            paneles.add(panel);
//        }
//        return paneles;
        List<PanelCartaMano> paneles = new java.util.ArrayList<>();

        for (CartaDTO cartaDTO : cartasDTO) {
            PanelCartaMano panel = new PanelCartaMano();
            panel.setCarta(cartaDTO);   // ← dibuja la carta real

            panel.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    intentarJugarCarta(cartaDTO);
                }
            });

            paneles.add(panel);
        }
        return paneles;
    }

    private void intentarJugarCarta(CartaDTO cartaSeleccionada) {
        control.jugarCarta(cartaSeleccionada);
    }

    private void actualizarNumeroCartas() {
        panelInfoJugadorPrincipal.actualizarNumeroCartas(modelo.getManoJugadorLocal().size());
    }

    private void actualizarCartaDescarte() {
        CartaDTO tope = modelo.getCartaEnTope();
        if (tope != null) {
            panelDescarte.removeAll();
            panelDescarte.setLayout(new java.awt.BorderLayout());
            PanelCartaMano cartaVisual = new PanelCartaMano();
            cartaVisual.setCarta(tope);
            panelDescarte.add(cartaVisual, java.awt.BorderLayout.CENTER);
            panelDescarte.revalidate();
            panelDescarte.repaint();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblRuleta;
    private javax.swing.JPanel panelCentral;
    private MVC_JugarTurno.PanelCarta panelDescarte;
    private javax.swing.JPanel panelEste;
    private javax.swing.JPanel panelFondo;
    private MVC_JugarTurno.PanelInformacionJugador panelInfoJugador1;
    private MVC_JugarTurno.PanelInformacionJugador panelInfoJugador2;
    private MVC_JugarTurno.PanelInformacionJugador panelInfoJugador3;
    private MVC_JugarTurno.PanelInformacionJugador panelInfoJugadorPrincipal;
    private javax.swing.JPanel panelMano;
    private MVC_JugarTurno.PanelCarta panelMazo;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelOeste;
    private javax.swing.JPanel panelPosaCartas;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane scrollMano;
    private javax.swing.JLayeredPane tablero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
//        List<CartaDTO> manoActualizada = modelo.getManoJugadorActual();
//
//        List<PanelCarta> cartasVisuales = generarPanelesDeMano(manoActualizada);
//
//        mostrarMano(cartasVisuales);
//
//        actualizarCartaDescarte();
//
//        EstadoPartidaDTO estado = modelo.getEstado();
//        if (estado != null && estado.isEsperandoColor()) {
//            pedirColorUsuario();
//        }
        List<CartaDTO> manoActualizada = modelo.getManoJugadorLocal();
        List<PanelCartaMano> cartasVisuales = generarPanelesDeMano(manoActualizada);
        mostrarMano(cartasVisuales);

        actualizarCartaDescarte();

        actualizarNumeroCartas();

        this.revalidate();
        this.repaint();

        EstadoPartidaDTO estado = modelo.getEstado();
        if (estado != null && estado.isEsperandoColor() && !pidiendoColor) {
            pidiendoColor = true;
            pedirColorUsuario();
        }
    }

    @Override
    public void notificarError(String mensaje) {
        mostrarError(mensaje);
    }

}
