<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.itson</groupId>
    <artifactId>UNO_Spin</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>../UNO-Interfaces</module>
        <module>../UNO-DTOs</module>
        <module>../UNO_Dominio</module>
        <module>../UNO-Serializador</module>
        <module>../UNO-Deserializador</module>
        <module>../UNO-ConexionSalida</module>
        <module>../UNO-ConexionEntrada</module>
        <module>../UNO-Adapter</module>
        <module>../UNO-Control</module>
        <module>../UNO-EstadoPartida</module>
        <module>../UNO-CoordinadorFiltros</module>
        <module>../UNO_Principal</module>
        <module>../UNO-Ensamblador</module>
    </modules>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>