/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MVC_JugarTurno;

import DTOs.JugadorResumenDTO;

/**
 *
 * @author saula
 */
public class PanelInformacionJugador extends javax.swing.JPanel {

    /**
     * Creates new form PanelInformacionJugador
     */
    public PanelInformacionJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFoto = new javax.swing.JPanel();
        lblFotoJugador = new javax.swing.JLabel();
        PanelNombre = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        panelCartas = new javax.swing.JPanel();
        lblNumCartas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 84, 182));

        panelFoto.setBackground(new java.awt.Color(31, 84, 182));
        panelFoto.setMaximumSize(new java.awt.Dimension(100, 100));
        panelFoto.setPreferredSize(new java.awt.Dimension(100, 100));
        panelFoto.setLayout(new java.awt.BorderLayout());

        lblFotoJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/default-profile-picture-icon-high-resolution-high-resolution-default-profile-picture-icon-symbolizing-no-display-picture-360167031.png"))); // NOI18N
        lblFotoJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelFoto.add(lblFotoJugador, java.awt.BorderLayout.CENTER);

        PanelNombre.setBackground(new java.awt.Color(31, 84, 182));
        PanelNombre.setLayout(new java.awt.BorderLayout());

        lblNombreUsuario.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(204, 204, 255));
        lblNombreUsuario.setText("SaulinPirulin");
        PanelNombre.add(lblNombreUsuario, java.awt.BorderLayout.CENTER);

        panelCartas.setBackground(new java.awt.Color(31, 84, 182));
        panelCartas.setLayout(new java.awt.BorderLayout());

        lblNumCartas.setFont(new java.awt.Font("Arial Black", 1, 32)); // NOI18N
        lblNumCartas.setForeground(new java.awt.Color(204, 204, 255));
        lblNumCartas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumCartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Numcartas.png"))); // NOI18N
        lblNumCartas.setText("5");
        panelCartas.add(lblNumCartas, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(panelCartas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCartas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarNumeroCartas(int cant) {
        lblNumCartas.setText(String.valueOf(cant));
    }
    
    public void actualizarNombreJugador(String nombre){
        lblNombreUsuario.setText(nombre);
    }

    public void actualizarInformacion(JugadorResumenDTO jugador) {
        if (jugador == null) {
            ocultarJugador();
            return;
        }

        actualizarNombreJugador(jugador.getNombreUsuario());
        actualizarNumeroCartas(jugador.getCantidadDeCartas());
        setVisible(true);
    }

    public void limpiar() {
        lblNombreUsuario.setText("---");
        lblNumCartas.setText("0");
    }

    public void ocultarJugador() {
        limpiar();
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNombre;
    private javax.swing.JLabel lblFotoJugador;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNumCartas;
    private javax.swing.JPanel panelCartas;
    private javax.swing.JPanel panelFoto;
    // End of variables declaration//GEN-END:variables
}
