package MVC_JugarTurno;

import DTOs.CartaDTO;
import DTOs.JugadorResumenDTO;
import Enums.EstadoFinalizacion;
import Enums.TipoColor;
import MVC_Utilidades.ColoresJugador;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;

/**
 *
 * @author Abraham Coronel
 */
public class PantallaTurno extends javax.swing.JFrame implements ISuscriptor {

    private static final int CARD_W = 95;
    private static final int CARD_H = 130;
    private static final int OVERLAP = 20;   // es lo que se desplaza la carta para empalmarse
    private static final int PAD_L = OVERLAP; // para que la primera se vea completa
    private static final int PAD_R = 10;
    private final UnoSpinControlador control;
    private final IModeloVista modelo;
    private boolean pidiendoColor = false;
    private String solicitudFinalizacionAtendida;
    private EstadoFinalizacion ultimoResultadoFinalizacion;
    private boolean tablaFinalMostrada;
    private Map<TipoColor, TipoColor> coloresLocales = new java.util.HashMap<>();

    public PantallaTurno(IModeloVista modelo, UnoSpinControlador control) {
        this.control = control;
        this.modelo = modelo;
        Map<TipoColor, TipoColor> cargados = ColoresJugador.getColores();
        if (cargados != null) {
            this.coloresLocales = cargados;
        }
        initComponents();
        configurarScroll();
        configurarPanelMano();
        configurarEventosScroll();

        configurarCarruselMano(7);
        ajustarAnchoMano();

        panelMazo.agregarClickListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                control.robarCarta();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        panelSur = new javax.swing.JPanel();
        panelInfoJugadorPrincipal = new MVC_JugarTurno.PanelInformacionJugador();
        scrollMano = new javax.swing.JScrollPane();
        panelMano = new javax.swing.JPanel();
        panelOeste = new javax.swing.JPanel();
        panelInfoJugador3 = new MVC_JugarTurno.PanelInformacionJugador();
        panelNorte = new javax.swing.JPanel();
        panelInfoJugador2 = new MVC_JugarTurno.PanelInformacionJugador();
        jButton1 = new javax.swing.JButton();
        panelEste = new javax.swing.JPanel();
        panelInfoJugador1 = new MVC_JugarTurno.PanelInformacionJugador();
        panelCentral = new javax.swing.JPanel();
        tablero = new javax.swing.JLayeredPane();
        lblRuleta = new javax.swing.JLabel();
        panelPosaCartas = new javax.swing.JPanel();
        panelDescarte = new MVC_JugarTurno.PanelCarta();
        panelMazo = new MVC_JugarTurno.PanelCarta();

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 84, 182));

        panelFondo.setLayout(new java.awt.BorderLayout());

        panelSur.setBackground(new java.awt.Color(31, 84, 182));
        panelSur.add(panelInfoJugadorPrincipal);

        scrollMano.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollMano.setMaximumSize(new java.awt.Dimension(100, 100));
        scrollMano.setViewportView(panelMano);

        panelSur.add(scrollMano);

        panelFondo.add(panelSur, java.awt.BorderLayout.PAGE_END);

        panelOeste.setBackground(new java.awt.Color(31, 84, 182));
        panelOeste.add(panelInfoJugador3);

        panelFondo.add(panelOeste, java.awt.BorderLayout.LINE_START);

        panelNorte.setBackground(new java.awt.Color(31, 84, 182));

        jButton1.setText("Finalizar Partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNorteLayout = new javax.swing.GroupLayout(panelNorte);
        panelNorte.setLayout(panelNorteLayout);
        panelNorteLayout.setHorizontalGroup(
            panelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNorteLayout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(panelInfoJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(156, 156, 156))
        );
        panelNorteLayout.setVerticalGroup(
            panelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNorteLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelInfoJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelNorteLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton1))
        );

        panelFondo.add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelEste.setBackground(new java.awt.Color(31, 84, 182));
        panelEste.add(panelInfoJugador1);

        panelFondo.add(panelEste, java.awt.BorderLayout.LINE_END);

        panelCentral.setBackground(new java.awt.Color(31, 84, 182));

        tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRuleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ruleta.png"))); // NOI18N
        lblRuleta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tablero.add(lblRuleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 425));

        javax.swing.GroupLayout panelPosaCartasLayout = new javax.swing.GroupLayout(panelPosaCartas);
        panelPosaCartas.setLayout(panelPosaCartasLayout);
        panelPosaCartasLayout.setHorizontalGroup(
            panelPosaCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPosaCartasLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelDescarte, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPosaCartasLayout.setVerticalGroup(
            panelPosaCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPosaCartasLayout.createSequentialGroup()
                .addGroup(panelPosaCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDescarte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tablero.setLayer(panelPosaCartas, javax.swing.JLayeredPane.PALETTE_LAYER);
        tablero.add(panelPosaCartas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, 130));

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablero)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablero)
        );

        panelFondo.add(panelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelFondo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EstadoPantallaTurnoDTO estado = modelo.getEstadoPantalla();
        if (estado != null && estado.getJugadorLocal() != null
                && PanelFinalizarPartida.mostrarDialogo(this)) {
            control.solicitarFinalizacion(estado.getJugadorLocal());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void configurarCarruselMano(int cartasVisibles) {
        int step = CARD_W - OVERLAP;
        int visibleW = PAD_L + CARD_W + (cartasVisibles - 1) * step + PAD_R;
        int visibleH = CARD_H + 20;

        scrollMano.setPreferredSize(new java.awt.Dimension(visibleW, visibleH));
        scrollMano.setMinimumSize(new java.awt.Dimension(visibleW, visibleH));

        // para que se aplique
        scrollMano.revalidate();
    }

    private void configurarScroll() {
        scrollMano.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollMano.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        // ocultar visualmente la barra
        scrollMano.getHorizontalScrollBar().setPreferredSize(new java.awt.Dimension(0, 0));

        scrollMano.setOpaque(false);
        scrollMano.getViewport().setOpaque(false);
        scrollMano.setBorder(null);
    }

    private void configurarPanelMano() {
        // Solapado real (gap negativo)
        panelMano.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, -OVERLAP, 0));

        // margen para que la primera carta se vea completa
        panelMano.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, PAD_L, 0, PAD_R));
        panelMano.setOpaque(false);
    }

    private void configurarEventosScroll() {
        scrollMano.addMouseWheelListener(e -> {
            JScrollBar bar = scrollMano.getHorizontalScrollBar();
            bar.setValue(bar.getValue() + e.getWheelRotation() * 45);
            e.consume();
        });
    }

    private void mostrarMano(List<PanelCartaMano> cartas) {
        panelMano.removeAll();
        for (PanelCartaMano c : cartas) {
            panelMano.add(c);
        }
        ajustarAnchoMano();
    }

    private void ajustarAnchoMano() {
        int n = panelMano.getComponentCount();

        int step = CARD_W - OVERLAP; // avance real por carta
        int width = PAD_L + (n == 0 ? 0 : (CARD_W + (n - 1) * step)) + PAD_R;
        int height = CARD_H + 10;

        panelMano.setPreferredSize(new java.awt.Dimension(width, height));
        panelMano.revalidate();
        panelMano.repaint();
    }

    public void mostrarMensaje(String mensaje, String titulo, int tipoMensaje) {
        JOptionPane.showMessageDialog(
                this,
                mensaje,
                titulo,
                tipoMensaje
        );
    }

    public void mostrarError(String mensaje) {
        mostrarMensaje(mensaje, "Movimiento no permitido", javax.swing.JOptionPane.WARNING_MESSAGE);
    }

    public int mostrarOpciones(String mensaje, String titulo, Object[] opciones) {
        return JOptionPane.showOptionDialog(this, mensaje, titulo,
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null, opciones, opciones[0]);
    }

    private void pedirColorUsuario() {
        TipoColor[] coloresBase = {
            TipoColor.ROJO, TipoColor.AZUL,
            TipoColor.VERDE, TipoColor.AMARILLO
        };
        String[] opcionesVisuales = new String[coloresBase.length];
        for (int i = 0; i < coloresBase.length; i++) {
            TipoColor colorLocal = this.coloresLocales.getOrDefault(coloresBase[i], coloresBase[i]);
            opcionesVisuales[i] = colorLocal.toString();
        }
        int seleccion = mostrarOpciones("Has jugado un comodin. Selecciona el nuevo color:", "Cambio de Color", opcionesVisuales);
        if (seleccion >= 0) {
            control.seleccionarColor(coloresBase[seleccion]);
        }
        pidiendoColor = false;
    }

    private List<PanelCartaMano> generarPanelesDeMano(List<CartaDTO> cartasDTO) {
        List<PanelCartaMano> paneles = new java.util.ArrayList<>();
        if (cartasDTO == null || this.coloresLocales == null) {
            return paneles;
        }
        for (CartaDTO cartaDTO : cartasDTO) {
            PanelCartaMano panel = new PanelCartaMano();
            if (cartaDTO.getColor() != null && this.coloresLocales.containsKey(cartaDTO.getColor())) {
                cartaDTO.setColor(this.coloresLocales.get(cartaDTO.getColor()));
            }
            panel.setCarta(cartaDTO);   //dibuja la carta real
            panel.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    intentarJugarCarta(cartaDTO);
                }
            });

            paneles.add(panel);
        }
        return paneles;
    }

    private void intentarJugarCarta(CartaDTO cartaSeleccionada) {
        control.jugarCarta(cartaSeleccionada);
    }

    private void actualizarCartaDescarte(EstadoPantallaTurnoDTO estadoPantalla) {
        if (this.coloresLocales == null) {
            this.coloresLocales = ColoresJugador.getColores();
        }
        CartaDTO tope = estadoPantalla.getCartaEnDescarte();
        if (tope != null) {
            panelDescarte.removeAll();
            panelDescarte.setLayout(new java.awt.BorderLayout());
            PanelCartaMano cartaVisual = new PanelCartaMano();
            if (tope.getColor() != null && this.coloresLocales.containsKey(tope.getColor())) {
                tope.setColor(this.coloresLocales.get(tope.getColor()));
            }
            cartaVisual.setCarta(tope);
            panelDescarte.add(cartaVisual, java.awt.BorderLayout.CENTER);
            panelDescarte.revalidate();
            panelDescarte.repaint();
        }
    }

    private void actualizarJugadores(EstadoPantallaTurnoDTO estadoPantalla) {
        panelInfoJugadorPrincipal.actualizarInformacion(estadoPantalla.getJugadorLocal());
        actualizarPanelRemoto(panelInfoJugador1, estadoPantalla.getJugadorEste());
        actualizarPanelRemoto(panelInfoJugador2, estadoPantalla.getJugadorNorte());
        actualizarPanelRemoto(panelInfoJugador3, estadoPantalla.getJugadorOeste());
    }

    private void actualizarPanelRemoto(PanelInformacionJugador panel, JugadorResumenDTO jugador) {
        if (jugador != null) {
            panel.actualizarInformacion(jugador);
            return;
        }
        panel.ocultarJugador();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblRuleta;
    private javax.swing.JPanel panelCentral;
    private MVC_JugarTurno.PanelCarta panelDescarte;
    private javax.swing.JPanel panelEste;
    private javax.swing.JPanel panelFondo;
    private MVC_JugarTurno.PanelInformacionJugador panelInfoJugador1;
    private MVC_JugarTurno.PanelInformacionJugador panelInfoJugador2;
    private MVC_JugarTurno.PanelInformacionJugador panelInfoJugador3;
    private MVC_JugarTurno.PanelInformacionJugador panelInfoJugadorPrincipal;
    private javax.swing.JPanel panelMano;
    private MVC_JugarTurno.PanelCarta panelMazo;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelOeste;
    private javax.swing.JPanel panelPosaCartas;
    private javax.swing.JPanel panelSur;
    private javax.swing.JScrollPane scrollMano;
    private javax.swing.JLayeredPane tablero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(IModeloVista modeloVista) {
        EstadoPantallaTurnoDTO estadoPantalla = modeloVista.getEstadoPantalla();
        if (estadoPantalla == null) {
            return;
        }

        if (!isVisible()) {
            setVisible(true);
        }

        List<CartaDTO> manoActualizada = estadoPantalla.getManoLocal() != null
                ? estadoPantalla.getManoLocal()
                : List.of();
        List<PanelCartaMano> cartasVisuales = generarPanelesDeMano(manoActualizada);
        mostrarMano(cartasVisuales);

        actualizarJugadores(estadoPantalla);
        actualizarCartaDescarte(estadoPantalla);

        this.revalidate();
        this.repaint();

        String msg = modeloVista.consumirMensajePendiente();
        if (msg != null && !msg.isBlank()) {
            mostrarError(msg);
        }

        if (estadoPantalla.isEsperandoColor() && !pidiendoColor && estadoPantalla.isTurnoLocal()) {
            pidiendoColor = true;
            SwingUtilities.invokeLater(this::pedirColorUsuario);
        }

        procesarFinalizacion(estadoPantalla);

    }

    private void procesarFinalizacion(EstadoPantallaTurnoDTO estadoPantalla) {
        if (estadoPantalla.getEstadoFinalizacion() == EstadoFinalizacion.EN_ESPERA_RESPUESTAS) {
            ultimoResultadoFinalizacion = null;
            tablaFinalMostrada = false;
            pedirRespuestaFinalizacion(estadoPantalla);
            return;
        }

        if (estadoPantalla.getEstadoFinalizacion() == EstadoFinalizacion.FINALIZADA
                || estadoPantalla.getEstadoFinalizacion() == EstadoFinalizacion.CANCELADA) {
            mostrarResultadoFinalizacion(estadoPantalla);
        }
    }

    private void pedirRespuestaFinalizacion(EstadoPantallaTurnoDTO estadoPantalla) {
        if (estadoPantalla.getResultadoFinalizacion() == null
                || estadoPantalla.getResultadoFinalizacion().getJugadorSolicitante() == null
                || estadoPantalla.getJugadorLocal() == null) {
            return;
        }

        JugadorResumenDTO solicitante = estadoPantalla.getResultadoFinalizacion().getJugadorSolicitante();
        if (solicitante.getId() == modelo.getIdJugadorLocal()) {
            return;
        }

        String claveSolicitud = solicitante.getId() + ":"
                + String.valueOf(estadoPantalla.getResultadoFinalizacion().getMensaje());
        if (claveSolicitud.equals(solicitudFinalizacionAtendida)) {
            return;
        }

        solicitudFinalizacionAtendida = claveSolicitud;
        String nombre = solicitante.getNombreUsuario() != null ? solicitante.getNombreUsuario() : "Otro jugador";
        boolean acepta = PanelResponderFinalizacion.mostrarDialogo(this, nombre);
        control.responderFinalizacion(estadoPantalla.getJugadorLocal(), acepta);
    }

    private void mostrarResultadoFinalizacion(EstadoPantallaTurnoDTO estadoPantalla) {
        EstadoFinalizacion estado = estadoPantalla.getEstadoFinalizacion();
        if (estado == EstadoFinalizacion.FINALIZADA && tablaFinalMostrada) {
            return;
        }

        if (estado == EstadoFinalizacion.CANCELADA && estado == ultimoResultadoFinalizacion) {
            return;
        }

        ultimoResultadoFinalizacion = estado;
        if (estado == EstadoFinalizacion.CANCELADA) {
            mostrarMensaje("La finalizacion de la partida fue cancelada.", "Finalizar partida", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        tablaFinalMostrada = true;
        PanelTablaPosiciones.mostrarDialogo(this, estadoPantalla.getTablaPosiciones());
        cerrarPrograma();
    }

    private void cerrarPrograma() {
        dispose();
        System.exit(0);
    }

}
