/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVC_Sala;

import DTOs.JugadorResumenDTO;
import MVC_Utilidades.UtilidadesGraficas;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Abraham Coronel
 */
public class SalaEspera extends javax.swing.JFrame implements ISuscriptorSala {

    private IModeloSalaVista modeloVista;
    private ControladorSala controlador;

    public SalaEspera() {
        initComponents();
    }

    private void refrescarPanelJugadores(List<JugadorResumenDTO> jugadores) {
        PanelListaJugadores.removeAll();
        for (JugadorResumenDTO jugador : jugadores) {
            ImageIcon imagen = new ImageIcon(jugador.getRutaAvatar());
            ImageIcon avatar = UtilidadesGraficas.hacerAvatarCircular(imagen.getImage(), 60);

            PanelJugador tarjeta = new PanelJugador(
                    jugador.getNombreUsuario(), avatar, false
            );
            PanelListaJugadores.add(tarjeta);
        }
        PanelListaJugadores.revalidate();
        PanelListaJugadores.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        PanelEspera = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        btnListo = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        PanelListaJugadores = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        PanelFondo.setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("SALA ESPERA");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelFondo.add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        PanelEspera.setBackground(new java.awt.Color(0, 0, 255));
        PanelEspera.setForeground(new java.awt.Color(255, 255, 255));
        PanelEspera.setLayout(new java.awt.BorderLayout());

        PanelBotones.setBackground(new java.awt.Color(255, 255, 255));

        btnListo.setBackground(new java.awt.Color(255, 255, 255));
        btnListo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnListo.setForeground(new java.awt.Color(0, 0, 0));
        btnListo.setText("Listo!");

        btnAtras.setBackground(new java.awt.Color(255, 0, 0));
        btnAtras.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnAtras.setText("Atras");

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBotonesLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 635, Short.MAX_VALUE)
                .addComponent(btnListo)
                .addGap(64, 64, 64))
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListo)
                    .addComponent(btnAtras))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        PanelEspera.add(PanelBotones, java.awt.BorderLayout.PAGE_END);

        scroll.setOpaque(false);

        PanelListaJugadores.setBackground(new java.awt.Color(0, 0, 255));
        PanelListaJugadores.setLayout(new javax.swing.BoxLayout(PanelListaJugadores, javax.swing.BoxLayout.LINE_AXIS));
        scroll.setViewportView(PanelListaJugadores);

        PanelEspera.add(scroll, java.awt.BorderLayout.CENTER);

        PanelFondo.add(PanelEspera, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelEspera;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelListaJugadores;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnListo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(IModeloSalaVista modeloVista) {
        refrescarPanelJugadores(modeloVista.getJugadoresEnSala());
    }
}
