/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MVC_Sala;

import java.awt.Color;
import Enums.EstadoJugadorSala;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author angel
 */
public class PanelJugadorNice extends javax.swing.JPanel {

    private JLabel lblAvatar;
    private JLabel lblNombre;
    private JLabel lblEstado;

    public PanelJugadorNice() {
        initComponents();
        configurarEstiloPanel();
    }

    public PanelJugadorNice(String nombre, Icon avatar, EstadoJugadorSala estadoSala) {
        this();
        setDatosJugador(nombre, avatar);
        setEstado(estadoSala);
    }

    private void configurarEstiloPanel() {
        setBackground(Color.WHITE);

        setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 102, 255)),
                BorderFactory.createEmptyBorder(0, 0, 0, 12)
        ));

        setPreferredSize(new Dimension(500, 58));
        setMinimumSize(new Dimension(420, 58));
        setMaximumSize(new Dimension(520, 58));
    }

    public void setDatosJugador(String nombre, Icon avatar) {
        lblNombre.setText(nombre != null && !nombre.isBlank() ? nombre : "Jugador");

        if (avatar != null) {
            lblAvatar.setIcon(avatar);
            lblAvatar.setText("");
        } else {
            lblAvatar.setIcon(null);
            lblAvatar.setText("?");
        }
    }

    public void setEstado(EstadoJugadorSala estadoSala) {
        if (estadoSala == EstadoJugadorSala.CONFIRMADO) {
            lblEstado.setText("✓");
            lblEstado.setForeground(new Color(0, 170, 0));
        } else if (estadoSala == EstadoJugadorSala.CANCELADO) {
            lblEstado.setText("×");
            lblEstado.setForeground(new Color(220, 40, 40));
        } else {
            lblEstado.setText("...");
            lblEstado.setForeground(Color.GRAY);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
