/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MVC_Sala;

import Enums.EstadoJugadorSala;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.Icon;

/**
 *
 * @author Abraham Coronel
 */
public class PanelJugador extends javax.swing.JPanel {

    public PanelJugador(String nombre, Icon avatar, boolean aceptado, EstadoJugadorSala estadoSala) {
        initComponents();
        configurarEstiloPanel();
        setDatosJugador(nombre, avatar);
        setEstado(aceptado, estadoSala);
    }

    private void configurarEstiloPanel() {
        setBackground(new Color(135, 206, 235));

        setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY),
                BorderFactory.createEmptyBorder(8, 24, 8, 24)
        ));

        setMaximumSize(new Dimension(Integer.MAX_VALUE, 86));
        setPreferredSize(new Dimension(0, 86));
    }

    public void setDatosJugador(String nombre, Icon avatar) {
        if (nombre != null) {
            lblNombre.setText(nombre);
        }

        lblAvatar.setText("");

        if (avatar != null) {
            lblAvatar.setIcon(avatar);
        }
    }

    public void setEstado(boolean aceptado, EstadoJugadorSala estadoSala) {
        if (!aceptado) {
            lblEstado.setText("Solicitud pendiente");
            lblEstado.setForeground(Color.GRAY);
            return;
        }

        if (estadoSala == EstadoJugadorSala.CONFIRMADO) {
            lblEstado.setText("Confirmado");
            lblEstado.setForeground(new Color(0, 153, 0));
            return;
        }

        lblEstado.setText("Esperando...");
        lblEstado.setForeground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Jugador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAvatar)
                .addGap(122, 122, 122)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(lblEstado)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblAvatar)
                    .addComponent(lblEstado))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
