/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MVC_ConfigurarPartida;

/**
 *
 * @author Pride Factor Black
 */
public class PantallaConfigurarPartida extends javax.swing.JFrame implements ISuscriptor{
    private IControlConfgPartida controlador;
    private IModeloConfgPartida modelo;
    /**
     * Creates new form PantallaConfigurarPartida
     */
    public PantallaConfigurarPartida(IControlConfgPartida controlador, IModeloConfgPartida modelo) {
        this.modelo= modelo;
        this.controlador=controlador;
        
        initComponents();
        
        jsNumeroInicio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        jsNumeroFin.setModel(new javax.swing.SpinnerNumberModel(9, 0, 9, 1));
        jsNumComodines.setModel(new javax.swing.SpinnerNumberModel(8, 0, 8, 1));
        
        setLocationRelativeTo(null);
        this.modelo.agregarSuscriptor(this);
    }

    public PantallaConfigurarPartida() {
        initComponents();
        
        jsNumeroInicio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        jsNumeroFin.setModel(new javax.swing.SpinnerNumberModel(9, 0, 9, 1));
        jsNumComodines.setModel(new javax.swing.SpinnerNumberModel(8, 0, 8, 1));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lnl0 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        jsNumeroFin = new javax.swing.JSpinner();
        jsNumeroInicio = new javax.swing.JSpinner();
        jsNumComodines = new javax.swing.JSpinner();
        lbltextoRN3 = new javax.swing.JLabel();
        lbltextoRN2 = new javax.swing.JLabel();
        lbltextoRN1 = new javax.swing.JLabel();
        lblnumeros = new javax.swing.JLabel();
        lnltextoNC1 = new javax.swing.JLabel();
        lblNumCartas = new javax.swing.JLabel();
        lblNumComodines = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CUCP_btnAtras.png"))); // NOI18N
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, -1, -1));

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CUCP_btnSiguiente.png"))); // NOI18N
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSiguiente.setDefaultCapable(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        lnl0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/0.png"))); // NOI18N
        getContentPane().add(lnl0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        lbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9.png"))); // NOI18N
        getContentPane().add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));
        getContentPane().add(jsNumeroFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 50, -1));
        getContentPane().add(jsNumeroInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 50, -1));
        getContentPane().add(jsNumComodines, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        lbltextoRN3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbltextoRN3.setText("Hasta");
        getContentPane().add(lbltextoRN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        lbltextoRN2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbltextoRN2.setText("Desde");
        getContentPane().add(lbltextoRN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, 20));

        lbltextoRN1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbltextoRN1.setText("Rango de numeros");
        getContentPane().add(lbltextoRN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        lblnumeros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/numeros.png"))); // NOI18N
        getContentPane().add(lblnumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        lnltextoNC1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lnltextoNC1.setText("Numero de comodines");
        getContentPane().add(lnltextoNC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, 20));

        lblNumCartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rectangulo.png"))); // NOI18N
        getContentPane().add(lblNumCartas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        lblNumComodines.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rectangulo.png"))); // NOI18N
        getContentPane().add(lblNumComodines, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        lblTexto.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setText("Configuracion de la partida");
        getContentPane().add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 310, -1));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PantallaConfigurarPartida.png"))); // NOI18N
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            int numeroInicio = (Integer) jsNumeroInicio.getValue();
            int numeroFin = (Integer) jsNumeroFin.getValue();
            int numComodines = (Integer) jsNumComodines.getValue();

            controlador.procesarConfiguracion(numeroInicio, numeroFin, numComodines);

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingresa solo números válidos.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PantallaConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PantallaConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PantallaConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PantallaConfigurarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PantallaConfigurarPartida().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JSpinner jsNumComodines;
    private javax.swing.JSpinner jsNumeroFin;
    private javax.swing.JSpinner jsNumeroInicio;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblNumCartas;
    private javax.swing.JLabel lblNumComodines;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lblnumeros;
    private javax.swing.JLabel lbltextoRN1;
    private javax.swing.JLabel lbltextoRN2;
    private javax.swing.JLabel lbltextoRN3;
    private javax.swing.JLabel lnl0;
    private javax.swing.JLabel lnltextoNC1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(IModeloConfgPartida modelo) {
       if (modelo.isConfiguracionExitosa()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Partida configurada correctamente."
        );
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    modelo.getMensajeError(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }
}
